version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tracing"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vd2q86uzjrc0"
s3_prefix = "tracing"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
